### PR TITLE
add checks for no password attribute

### PR DESCRIPTION
**Pull request by anotherjesse**
add a test to make sure password fields aren't returned with user get/list

### CODE REVIEW

**Comment by termie** [comment]
should a keystone admin be allowed to get the password?

**Comment by anotherjesse** [comment]
I don't think so - an admin can reset passwords but not set

**Comment by termie** [comment]
an admin would be able to _set_ the password just by updating the user, no?

**Comment by anotherjesse** [comment]
that is correct - there is a test for that already as well

**Pull request merged**
