### PR TITLE
Binaries conflict with python-keystoneclient

### PR DESCRIPTION
**Pull request by zulcss**
keystonelight and python-keystoneclient binaries conflict, so call bin/keystone bin/keystone-server.

Signed-off-by: Chuck Short chuck.short@canonical.com

### CODE REVIEW

**Comment by termie** [comment]
I think keystoneclient should change their binary, mine came first by a long shot

**Comment by heckj** [comment]
Chuck - we're going to update the keystoneclient binary - it was accidentally changed on that side, we're fixing on that project

**Comment by termie** [comment]
per heckj's comments I'm going to close this, thanks for the heads up, Chuck :)

**Comment by ttx** [comment]
See https://bugs.launchpad.net/keystone/+bug/910484
For consistency with the rest of openstack (all CLI tools are named as the project, like "nova", "glance", or "swift") I think the CLI tool should be named "keystone". To be compatible with the change on keystoneheavy, the server should probably be called keystone-all.

**Pull request closed without merging**
