### PR TITLE
Fixed the 6 failing tests regarding role grants

### PR DESCRIPTION
**Pull request by dolph**

### CODE REVIEW

**Comment by termie** [comment]
I'm a little confused by this pull request, did the name of the methods in keystoneclient change _again_ in the last three days?

Additionally, from what I can tell this is duplicating work in the fix_master_kc branch, which fixes the issues due to the name change between essex-3 and master, could you explain more about which tests you are fixing and why?

**Comment by termie** [comment]
according to this: https://github.com/openstack/python-keystoneclient/blob/master/keystoneclient/v2_0/roles.py there is no such method as grant_role or the others you mention

**Comment by dolph** [comment]
Submitted corresponding changes to the client: https://review.openstack.org/#change,3636

A fresh pull of ksl running against python-keystoneclient-master has 6 test failures (2 test defs \* 3 iterations), due to the recent method name changes you're referring to.

From a conceptual perspective, tenants don't "have" users (e.g. add_user_to_tenant), except indirectly through roles. Additionally, "role-refs" are an implementation detail that should have never leaked to the api, I'm sure you'll agree.

Should I be working off a different branch?

**Comment by termie** [comment]
I don't support the change to the client, especially not right now.

You haven't been active in the KSL development channels (you are a member of the skype channel but not online) so you probably haven't noticed the work being done to fix those particular tests already, however there is now a pull request out that fixes them: https://github.com/termie/keystonelight/pull/30

From a conceptual standpoint KSL is not the same as Keystone and the data model used by Keystone is not the one in use by KSL. In KSL user membership to tenants is not predicated on them having a role within that tenant and that behavior is simply emulated to support the existing use cases. And I do agree that the implementation of "role-refs" is a travesty and required significant effort to emulate in the api.

Working against master is a decent approach, but you'll want to be part of the discussion about what is being worked on or you will run into issues like this again. In this case the pull request referenced above fixes the issues you were aiming at here.

**Pull request closed without merging**
